autoCorrect: true

build:
  maxIssues: 0
  weights:
    complexity: 1
    formatting: 1
    LongParameterList: 1
    comments: 1

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
  #  - 'FindingsReport'         If you exclude this, issues won't show on the console
  #  - 'BuildFailureReport'     This NEEDS to be commented out, the build won't fail if we exclude it

complexity:
  ComplexMethod:
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
  LargeClass:
    threshold: 350
  LongMethod:
    threshold: 30
  LongParameterList:
    threshold: 7
  TooManyFunctions:
    active: false

exceptions:
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions: ''

formatting:
  android: true
  ImportOrdering:
    active: true
    autoCorrect: true
  NoItParamInMultilineLambda:
    active: true

naming:
  PackageNaming:
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    privatePropertyPattern: '(_)?[A-Za-z][A-Za-z0-9]*'

style:
  ForbiddenComment:
    values: 'STOPSHIP'
  MaxLineLength:
    maxLineLength: 150
  ProtectedMemberInFinalClass:
    active: true
  ReturnCount:
    active: false
  TrailingWhitespace:
    active: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    excludeImports: 'kotlinx.android.synthetic.*'

empty-blocks:
  EmptyFunctionBlock:
    active: false # It's bugged, see https://github.com/arturbosch/detekt/issues/1684
